name: ShellCheck

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.sh'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.sh'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: '.'
        additional_files: '*.sh'
